   # Big Data Real-Time Analytics com Python e Spark
   
   # Cap 02

### Para gerar um arquivo PDF a partir do Jupyter Notebook, precisa ser instalado em seu computador:

#### Tex Live e Pandoc (linux)

#### info: http://pandoc.org/installing.html

## Computação com NumPy

In [1]:
# Importando o módulo Numpy
import numpy as np

## Criando Estrutura de Dados Numpy

In [2]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40])

In [3]:
# Criando um array bi-dimensional
array2 = np.array([[100, 83, 15], [42, 78, 0]])

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [6]:
# Verificando o formato(shape) do array
array1.shape

(4,)

In [7]:
# Verificando o formato(shape) do array
array2.shape

(2, 3)

In [8]:
# Verificando o número de dimensões
array2.ndim

2

## Em Python TUDO é objeto, com métodos e atibutos

### Método - realiza ação no objeto

### Atributo - característica do objeto

In [11]:
# Método 
array2.max()

100

In [12]:
# Atributo 
array2.ndim

2

## Criando estruturas de dados com arange

In [13]:
array3 = np.arange(15)

In [14]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 5)

In [16]:
array4

array([ 0,  5, 10])

## Criando estruturas de dados com linspace

In [17]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

## Criando estrutura de dados com outras funções 

### numpy.zeros

In [18]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### numpy.ones

In [19]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.eyes

In [20]:
# Produz uma Identity Matrix
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [21]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [22]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [23]:
# A função rand(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

### numpy.empty

In [24]:
array12 = np.empty((3,2)); array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.tile

In [25]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [26]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [27]:
np.tile(np.array([[9, 4], [3, 7]]), (2, 2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])